app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
 * Home Page
 * Created by Saurabh Kadam
 * Created Date 13-Oct-2016
 */

Route::get('/', ['uses'=>'HomeController@index', 'as' => 'home']);
Route::get('prepay', ['uses'=>'PrepayController@index', 'as' => 'prepay']);
Route::post('prepaystore', ['uses'=>'PrepayController@store', 'as' => 'prepay.store']);
Route::post('prepaysignin', ['uses'=>'PrepayController@signin', 'as' => 'prepay.signin']);
Route::get('prepaydashboard', ['uses'=>'PrepayController@dashboard', 'as' => 'prepay.dashboard']);
Route::post('prepayjob', ['uses'=>'PrepayController@checkjob_code', 'as' => 'prepay.job']);
//Route::get('prepayphoto', ['uses'=>'PrepayController@dashboard', 'as' => 'prepay.photo']);


Route::group(["namespace" => 'Admin', "prefix" => "admin"], function() {
    Route::get('/', ['uses'=>'SiteController@index', 'as' => 'home']);
    Route::get('signin', ['uses'=>'SiteController@index', 'as' => 'admin.signin']);
    Route::post('signin', ['uses'=>'SiteController@signin', 'as' => 'admin.signin']);
    Route::get('logout', ['uses'=>'SiteController@logout', 'as' => 'admin.logout']);    
    Route::get('admin',['uses'=>'SiteController@adminDashboard', 'as' => 'admin']);
    Route::get('dashboard', ['uses'=>'SiteController@dashboard', 'as' => 'admin.dashboard']);    

    /*
     * School Management
     * Created by Rahul Gupta
     * Created Date 01-Oct-2016
     */

    route::resource('school', 'SchoolController', ['except' => ['destroy']]);
    route::get('school/delete/{school}', ['uses'=>'SchoolController@destroy' , 'as'=>'admin.school.destroy']);

    /*
     * Grade Management
     * Created by Rahul Gupta
     * Created Date 04-Oct-2016
     */
    route::resource('student', 'StudentController', ['except' => ['destroy']]);
    route::get('student/delete/{student}', ['uses'=>'StudentController@destroy' , 'as'=>'admin.student.destroy']);
    route::get('student/studentlist/{grade_id}', ['uses'=>'StudentController@studentListByGradeID' , 'as'=>'admin.student.studentlist']);
    /*
     * Prepay Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('prepayjob', 'PrepayjobController', ['except' => ['destroy']]);
    route::get('prepayjob/delete/{job}', ['uses'=>'PrepayjobController@destroy' , 'as'=>'admin.prepayjob.destroy']);
    
    
    /*
     * Re-Order Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('reorderjob', 'ReorderjobController', ['except' => ['destroy']]);
    route::get('reorderjob/delete/{job}', ['uses'=>'ReorderjobController@destroy' , 'as'=>'admin.reorderjob.destroy']);
    
    /*
     * Miscellaneous Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('miscellaneousjob', 'MiscellaneousjobController', ['except' => ['destroy']]);
    route::get('miscellaneousjob/delete/{job}', ['uses'=>'miscellaneousjob@destroy' , 'as'=>'admin.miscellaneousjob.destroy']);
    
    /*
     * Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('job', 'JobController', ['except' => ['destroy']]);
    route::get('job/delete/{job}', ['uses'=>'JobController@destroy' , 'as'=>'admin.job.destroy']);
    

    /*
     * Grade Management
     * Created by Rahul Gupta
     * Created Date 04-Oct-2016
     */
    route::resource('grade', 'GradeController', ['except' => ['destroy']]);
    route::get('grade/delete/{grade}', ['uses'=>'GradeController@destroy' , 'as'=>'admin.grade.destroy']);    
    route::get('grade/gradelist/{school_id}', ['uses'=>'GradeController@gradeListBySchoolID' , 'as'=>'admin.grade.gradelist']);

    /*
     * School Management
     * Created by Saurabh Kadam
     * Created Date 01-Oct-2016
     */
    Route::resource('message','MessageController');
    
    /*
     * Package Management
     * Created by Saurabh Kadam
     * Created Date 03-Oct-2016
     */
    Route::resource('package','PackageController');
    Route::resource('packageprofile','PackageprofileController');

    /*
     * Image Management
     * Created by Saurabh Kadam
     * Created Date 04-Oct-2016
     */
    Route::resource('image','ImageController');    

    /*
     * Item Management
     * Created by Saurabh Kadam
     * Created Date 04-Oct-2016
     */
    Route::resource('item','ItemController');
    /*
     * Contact Management
     * Created by Saurabh Kadam
     * Created Date 05-Oct-2016
     */
    Route::resource('contact','ContactController');
    /*
     * Job Management
     * Created by Rahul Gupta
     * Created Date 07-Oct-2016
     */
    route::resource('uploadImage', 'UploadImageController', ['except' => ['destroy']]);
    route::get('uploadImage/delete/{job}', ['uses'=>'UploadImageController@destroy' , 'as'=>'admin.uploadImage.destroy']);
    route::post('uploadImage/upload', ['uses'=>'UploadImageController@upload' , 'as'=>'admin.uploadImage.upload']);
    route::post('uploadImage/remove', ['uses'=>'UploadImageController@removeImage' , 'as'=>'admin.uploadImage.remove']);
    route::get('uploadImage/getImages/{uploadImage}', ['uses'=>'UploadImageController@getImage' , 'as'=>'admin.uploadImage.get']);


     /*
     * My Profile
     * Created by Saurabh Kadam
     * Created Date 20-Oct-2016
     */
    Route::resource('profile','ProfileController'); 
    Route::post('profilepassword', ['uses'=>'ProfileController@password', 'as' => 'admin.profile.password']);  
    //route::post('ProfileController/password', ['uses'=>'ProfileController@password' , 'as'=>'admin.profile.password']);



    /*
     * My Profile
     * Created by Saurabh Kadam
     * Created Date 21-Oct-2016
     */
    Route::resource('customer','CustomerController'); 
    //Route::post('profilepassword', ['uses'=>'ProfileController@password', 'as' => 'admin.profile.password']);  
});

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $table = "fp_imagetype";

     public function scopeSearchByKeyword($query, $keyword)
    {
        if ($keyword!='') {
            $query->where(function ($query) use ($keyword) {
                $query->orWhere("image_title", "LIKE","%$keyword%");
                
            });
        }
        return $query;
    }
}

app/Images.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Images extends Model
{
    protected $table = "fp_images";
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\ImageRequest;
use Illuminate\Support\Facades\Redirect;
use App\Image;
use View;
use Auth;
use Input;

class ImageController extends MainController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct() {                
        parent::__construct();
    }
    public function index(Request $request)
    {
        $keyword = $request->input('search_keyword');
        $this->data['image_data'] = Image::SearchByKeyword($keyword)->Select('id','image_title','status','created_at')->orderBy('id', 'DESC')->paginate(10);        
        return View::make('admin.image.list',$this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
            return View::make('admin.image.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ImageRequest $request)
    {
        $image_data = new Image();       
        $image_data ->image_title    = $request->input('image_type');
        if($image_data->save())
            return Redirect::route('admin.image.store')->with(array('flash_message'=>'Image successfully added', 'flash_action'=>'success'));
        else
            return Redirect::route('admin.image.create')->with(array('flash_message'=>'Image not saved successfully!', 'flash_action'=>'danger'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $image = Image::find($id);
        $data = array(
                      'image'  => $image,
                       'id'=>$id
                );
        return View::make('admin.image.create')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ImageRequest $request)
    {
        $id = $request->input('id');
        $image_data = Image::find($id);       
        $image_data ->image_title    = $request->input('image_type');
        $image_data ->status    = $request->input('status');
        if($image_data->save())
            return Redirect::route('admin.image.index')->with(array('flash_message'=>'Image successfully updated!', 'flash_action'=>'success'));
        else
            return Redirect::route('admin.image.edit', $id)->with(array('flash_message'=>'Image not updated successfully!', 'flash_action'=>'danger'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/image/create.blade.php
@extends('admin.layouts.master')
{{-- Page title --}}
@section('title')
    Image
    @parent
@stop

{{-- page level styles --}}
@section('header_styles')

    <link href="{{ asset('public/assets/css/pages/form2.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/css/pages/form3.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/vendors/jasny-bootstrap/css/jasny-bootstrap.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/vendors/intl-tel-input/build/css/intlTelInput.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/vendors/validation/dist/css/bootstrapValidator.min.css') }}" rel="stylesheet"/>
    <style type='text/css'>
        .form-group.required .control-label:after { 
            content:"*";
            color:red;
        }
    </style>
@stop

{{-- Page content --}}
@section('content')
    <?php
        $title = "Create";
        $action = route('admin.image.store');
        $method = '';
        if(!empty($image->id)){
            $title = "Edit";
            $action = route('admin.image.update', $image->id);
            $method = '<input type="hidden" name="_method" value="PUT" />';
        }

    ?>
    <section class="content-header">
        <!--section starts-->
        <h1>Image</h1>

    </section>
    <!--section ends-->
    <section class="content">
        <!--main content-->
        <div class="row">            
            <div class="col-md-12">                
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <i class="livicon" data-name="rocket" data-size="16" data-loop="true" data-c="#fff"
                               data-hc="white"></i>
                            {{$title}}
                        </h3>                        
                        <span class="pull-right clickable">
                            <i class="glyphicon glyphicon-chevron-up"></i>
                        </span>

                    </div>                    
                    <div class="panel-body">
                        <div class="row">
                        @if (session('flash_message'))
                        <div class="flash-message">
                            <div class="alert alert-{{session('flash_action')}}">
                                <p>{{session('flash_message')}}</p>
                            </div>
                        </div>
                        @endif
                            <form action="{{$action}}" method="POST" role="form">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                                <input type="hidden" name="id" value="{{@$image->id}}" />
                                <?php echo $method; ?>                       
                                <div class="row">
                                    
                                    <div class="col-xs-12 col-md-12">                                        
                                        <div class="form-group required {{ $errors->first('image_type', 'has-error') }}">                                            
                                            <label class="control-label">Image Type</label>
                                           <input type="text" name="image_type" id="image_type" class="form-control input-md" placeholder="Image Type" value="{{!empty($image->image_title)?$image->image_title:Input::old('image_type')}}">
                                           {!! $errors->first('image_type', '<span class="help-block">:message</span>') !!}
                                        </div>
                                    </div>
                                </div>

                                  @if(isset($image->id) && !empty($image->id))
                                    <div class="row">                                    
                                        <div class="col-xs-12 col-md-12">
                                            <div class="form-group {{ $errors->first('status', 'has-error')}}">
                                                <label class="control-label">Status</label>                                        
                                                <?php                                        
                                                $active = ($image->status == '1')?'checked="checked"':"";
                                                $inactive = ($image->status == '0')?'checked="checked"':"";
                                                ?>                                        
                                                <input name="status" value="1" type="radio" <?php echo $active; ?>/> Active <input type="radio" name="status" value="0" <?php echo $inactive; ?>/> Inactive
                                                {!! $errors->first('status', '<span class="help-block">:message</span>') !!}
                                            </div>                                    
                                        </div>
                                    </div>
                                    @endif
                                
                                <div class="row">                                    
                                    <div class="col-xs-12 col-md-12">
                                        <input type="submit" class="btn btn-primary btn-block btn-md btn-responsive create-btn" value="Create">
                                    </div>

                                </div>    
                            </form>
                        </div>                        
                    </div>
                </div>                
            </div>
        </div>
        
        <!--row ends-->
    </section>
    <!-- content -->
@stop

{{-- page level scripts --}}
@section('footer_scripts')    
    <script src="{{ asset('public/assets/vendors/jasny-bootstrap/js/jasny-bootstrap.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ asset('public/assets/vendors/validation/dist/js/bootstrapValidator.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ asset('public/assets/vendors/intl-tel-input/build/js/intlTelInput.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ asset('public/assets/js/pages/validation.js') }}" type="text/javascript"></script>
@stop

resources/views/admin/image/list.blade.php
@extends('admin.layouts.master')
{{-- Page title --}}
@section('title')
    Image
    @parent
@stop

{{-- page level styles --}}
@section('header_styles')

    <link href="{{ asset('public/assets/css/pages/form2.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/css/pages/form3.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/vendors/jasny-bootstrap/css/jasny-bootstrap.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/vendors/intl-tel-input/build/css/intlTelInput.css') }}" rel="stylesheet"/>
    <link href="{{ asset('public/assets/vendors/validation/dist/css/bootstrapValidator.min.css') }}" rel="stylesheet"/>
    <style type='text/css'>
        .form-group.required .control-label:after { 
            content:"*";
            color:red;
        }
    </style>
@stop

{{-- Page content --}}
@section('content')

    <section class="content-header">
        <!--section starts-->
        <h1>Image</h1>
    </section>
    <!--section ends-->
    <section class="content">
    <div class="row">
        <div class="col-md-12">            
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="panel panel-primary filterable">
                <div class="panel-heading clearfix">
                    <div class="panel-heading clearfix  ">
                        <div class="caption pull-left">
                            <i class="livicon" data-name="list" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                            Image List                        
                        </div>
                        <div class="btn-group pull-right">
                            <a href="{{route('admin.image.create')}}"  class=" btn btn-warning add-anc">Add Image Type</a>
                        </div>
                    </div>    
                </div>
                <div class="panel-body table-responsive">
                    @if (session('flash_message'))
                    <div class="flash-message">
                        <div class="alert alert-{{session('flash_action')}}">
                            <p>{{session('flash_message')}}</p>
                        </div>
                    </div>
                    @endif    
                    <form action="{{ route('admin.image.index') }}" method="GET" role="form">                    
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="action" value="" />
                    <div class="row">
                        <div class="col-xs-12 col-md-12">                                        
                            <div class="form-group {{ $errors->first('', 'has-error') }}">
                                    <label class="control-label">Search</label>
                                        <input type="text" name="search_keyword" id="search_keyword" class="form-control" style="width:320px;" placeholder="Search by image type" value="{{Input::old('search_keyword')}}">    
                                    <input type="submit" class="btn btn-primary" style="width:120px;margin-top:-58px;margin-left:404px;" value="Search">
                            </div>
                        </div>
                    </div> 
                    </form>                
                    <table class="table table-striped table-bordered" id="table-entity">
                        <thead>
                            <tr>                                    
                                <th style="width: 5%;text-align:center;">#</th>
                                <th style="width: 20%;text-align:center;">Image Type</th>
                                <th style="width: 20%;text-align:center;">Status</th>
                                <th style="width: 20%;text-align:center;">Created Date</th>
                                <th style="width: 20%;text-align:center;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(!empty($image_data))                                                               
                            @foreach($image_data as $objEntity)
                            <tr>
                                <td style="text-align:center;">{{$objEntity['id']}}</td>                                    
                                <td style="text-align:center;">{{$objEntity['image_title']}}</td>
                                <td style="text-align:center;">{{($objEntity['status']=='1')?'Active':'Inactive'}}</td>
                                <td style="text-align:center;">{{$objEntity['created_at']}}</td>
                                <td style="width: 30%;text-align:center;">
                                    <a href="{{route('admin.image.edit',$objEntity['id'])}}" id="edit" name="edit" class=" btn btn-warning add-anc">Edit</a>
                                    <a href="{{route('admin.image.destroy',$objEntity['id'])}}"  id="" onclick="return confirm('Are you sure?');" class="btn btn-danger add-anc del-msg">Delete</a>
                                </td>
                            </tr>                                
                            @endforeach                            
                            @endif
                        </tbody>
                    </table>
                    <span style="width:100%;" class"pull-right">{!! $image_data->render() !!}</span>
                </div>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>     
</div>   
</section>
    <!-- content -->
    
@stop

{{-- page level scripts --}}
@section('footer_scripts')    
    <script src="{{ asset('public/assets/vendors/jasny-bootstrap/js/jasny-bootstrap.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ asset('public/assets/vendors/validation/dist/js/bootstrapValidator.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ asset('public/assets/vendors/intl-tel-input/build/js/intlTelInput.min.js') }}"
            type="text/javascript"></script>
    
    <script src="{{ asset('public/assets/js/pages/validation.js') }}" type="text/javascript"></script>
    
   
@stop