app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
 * Home Page
 * Created by Saurabh Kadam
 * Created Date 13-Oct-2016
 */

Route::get('/', ['uses'=>'HomeController@index', 'as' => 'home']);
Route::get('prepay', ['uses'=>'PrepayController@index', 'as' => 'prepay']);
Route::post('prepaystore', ['uses'=>'PrepayController@store', 'as' => 'prepay.store']);
Route::post('prepaysignin', ['uses'=>'PrepayController@signin', 'as' => 'prepay.signin']);
Route::get('prepaydashboard', ['uses'=>'PrepayController@dashboard', 'as' => 'prepay.dashboard']);
Route::post('prepayjob', ['uses'=>'PrepayController@checkjob_code', 'as' => 'prepay.job']);
//Route::get('prepayphoto', ['uses'=>'PrepayController@dashboard', 'as' => 'prepay.photo']);


Route::group(["namespace" => 'Admin', "prefix" => "admin"], function() {
    Route::get('/', ['uses'=>'SiteController@index', 'as' => 'home']);
    Route::get('signin', ['uses'=>'SiteController@index', 'as' => 'admin.signin']);
    Route::post('signin', ['uses'=>'SiteController@signin', 'as' => 'admin.signin']);
    Route::get('logout', ['uses'=>'SiteController@logout', 'as' => 'admin.logout']);    
    Route::get('admin',['uses'=>'SiteController@adminDashboard', 'as' => 'admin']);
    Route::get('dashboard', ['uses'=>'SiteController@dashboard', 'as' => 'admin.dashboard']);    

    /*
     * School Management
     * Created by Rahul Gupta
     * Created Date 01-Oct-2016
     */

    route::resource('school', 'SchoolController', ['except' => ['destroy']]);
    route::get('school/delete/{school}', ['uses'=>'SchoolController@destroy' , 'as'=>'admin.school.destroy']);

    /*
     * Grade Management
     * Created by Rahul Gupta
     * Created Date 04-Oct-2016
     */
    route::resource('student', 'StudentController', ['except' => ['destroy']]);
    route::get('student/delete/{student}', ['uses'=>'StudentController@destroy' , 'as'=>'admin.student.destroy']);
    route::get('student/studentlist/{grade_id}', ['uses'=>'StudentController@studentListByGradeID' , 'as'=>'admin.student.studentlist']);
    /*
     * Prepay Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('prepayjob', 'PrepayjobController', ['except' => ['destroy']]);
    route::get('prepayjob/delete/{job}', ['uses'=>'PrepayjobController@destroy' , 'as'=>'admin.prepayjob.destroy']);
    
    
    /*
     * Re-Order Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('reorderjob', 'ReorderjobController', ['except' => ['destroy']]);
    route::get('reorderjob/delete/{job}', ['uses'=>'ReorderjobController@destroy' , 'as'=>'admin.reorderjob.destroy']);
    
    /*
     * Miscellaneous Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('miscellaneousjob', 'MiscellaneousjobController', ['except' => ['destroy']]);
    route::get('miscellaneousjob/delete/{job}', ['uses'=>'miscellaneousjob@destroy' , 'as'=>'admin.miscellaneousjob.destroy']);
    
    /*
     * Job Management
     * Created by Rahul Gupta
     * Created Date 06-Oct-2016
     */
    route::resource('job', 'JobController', ['except' => ['destroy']]);
    route::get('job/delete/{job}', ['uses'=>'JobController@destroy' , 'as'=>'admin.job.destroy']);
    

    /*
     * Grade Management
     * Created by Rahul Gupta
     * Created Date 04-Oct-2016
     */
    route::resource('grade', 'GradeController', ['except' => ['destroy']]);
    route::get('grade/delete/{grade}', ['uses'=>'GradeController@destroy' , 'as'=>'admin.grade.destroy']);    
    route::get('grade/gradelist/{school_id}', ['uses'=>'GradeController@gradeListBySchoolID' , 'as'=>'admin.grade.gradelist']);

    /*
     * School Management
     * Created by Saurabh Kadam
     * Created Date 01-Oct-2016
     */
    Route::resource('message','MessageController');
    
    /*
     * Package Management
     * Created by Saurabh Kadam
     * Created Date 03-Oct-2016
     */
    Route::resource('package','PackageController');
    Route::resource('packageprofile','PackageprofileController');

    /*
     * Image Management
     * Created by Saurabh Kadam
     * Created Date 04-Oct-2016
     */
    Route::resource('image','ImageController');    

    /*
     * Item Management
     * Created by Saurabh Kadam
     * Created Date 04-Oct-2016
     */
    Route::resource('item','ItemController');
    /*
     * Contact Management
     * Created by Saurabh Kadam
     * Created Date 05-Oct-2016
     */
    Route::resource('contact','ContactController');
    /*
     * Job Management
     * Created by Rahul Gupta
     * Created Date 07-Oct-2016
     */
    route::resource('uploadImage', 'UploadImageController', ['except' => ['destroy']]);
    route::get('uploadImage/delete/{job}', ['uses'=>'UploadImageController@destroy' , 'as'=>'admin.uploadImage.destroy']);
    route::post('uploadImage/upload', ['uses'=>'UploadImageController@upload' , 'as'=>'admin.uploadImage.upload']);
    route::post('uploadImage/remove', ['uses'=>'UploadImageController@removeImage' , 'as'=>'admin.uploadImage.remove']);
    route::get('uploadImage/getImages/{uploadImage}', ['uses'=>'UploadImageController@getImage' , 'as'=>'admin.uploadImage.get']);


     /*
     * My Profile
     * Created by Saurabh Kadam
     * Created Date 20-Oct-2016
     */
    Route::resource('profile','ProfileController'); 
    Route::post('profilepassword', ['uses'=>'ProfileController@password', 'as' => 'admin.profile.password']);  
    //route::post('ProfileController/password', ['uses'=>'ProfileController@password' , 'as'=>'admin.profile.password']);



    /*
     * My Profile
     * Created by Saurabh Kadam
     * Created Date 21-Oct-2016
     */
    Route::resource('customer','CustomerController'); 
    //Route::post('profilepassword', ['uses'=>'ProfileController@password', 'as' => 'admin.profile.password']);  
});

app/Packageprofile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Packageprofile extends Model
{
    protected $table = "fp_package_profile";

    public function scopeSearchByKeyword($query, $keyword)
    {
        if ($keyword!='') {
            $query->where(function ($query) use ($keyword) {
                $query->where("package_profile_name", "LIKE","%$keyword%");                
            });
        }
        return $query;
    }
}

app/Http/Controllers/Admin/PackageprofileController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\PackageprofileRequest;
use Illuminate\Support\Facades\Redirect;
use App\Packageprofile;
use App\Package;
use File;
use Validator;
use View;
use Auth;
use Input;

class PackageprofileController extends MainController {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $keyword = $request->input('search_keyword');
        $this->data['packageprofile_data'] = Packageprofile::SearchByKeyword($keyword)->Select('id', 'package_profile_name', 'image')->orderBy('id', 'DESC')->paginate(10);
        return View::make('admin.packageprofile.list', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return View::make('admin.packageprofile.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PackageprofileRequest $request) {
        $packageprofile_data = new Packageprofile();
        $packageprofile_data->package_profile_name = $request->input('packageprofile_name');
        $path = base_path() . '/public/uploads/demo';
        $fileName = "";
        if (!empty(Input::file('packageprofile_image')) && Input::file('packageprofile_image')->getError() == 0)
            $fileName = $this->fileUpload(Input::file('packageprofile_image'), $path);
        $packageprofile_data->image = $fileName;
        if ($packageprofile_data->save()) {
            if (!empty($request->input('package'))) {
                $i = 1;
                foreach ($request->input('package') as $objPackage) {
                    $rules = array('package_name' => 'required', 'package_price' => 'required|integer');
                    $file = array('package_name' => $objPackage['package_name'], 'package_price' => $objPackage['package_price']);
                    $validator = Validator::make($file, $rules);
                    if (!$validator->fails()) {
                        $package_data = new Package();
                        $package_data->profile_id = $packageprofile_data->id;
                        $package_data->name = $objPackage['package_name'];
                        $package_data->price = $objPackage['package_price'];
                        $package_data->description = $objPackage['package_desc'];
                        $package_data->post_handling = $objPackage['ph'];
                        $package_data->image = $this->fileUpload(Input::file('package_image_' . $i), $path);
                        $package_data->save();
                    }
                    $i++;
                }
            }
            return Redirect::route('admin.packageprofile.store')->with(array('flash_message' => 'Packageprofile successfully added', 'flash_action' => 'success'));
        } else {
            return Redirect::route('admin.packageprofile.create')->with(array('flash_message' => 'Packageprofile not saved successfully!', 'flash_action' => 'danger'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $packageprofile = Packageprofile::find($id);
        $packages = Package::where('profile_id', $id)->get();
        $data = array(
            'packageprofile' => $packageprofile,
            'packages' => $packages,
            'id' => $id
        );
        return View::make('admin.packageprofile.create')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PackageprofileRequest $request) {
        $id = $request->input('id');
        $packageprofile_data = Packageprofile::find($id);
        $packageprofile_data->package_profile_name = $request->input('packageprofile_name');
        $path = base_path() . '/public/uploads/demo';
        if (!empty(Input::file('packageprofile_image')) && Input::file('packageprofile_image')->getError() == 0) {
            $fileName = $this->fileUpload(Input::file('packageprofile_image'), $path, $packageprofile_data->image);
        }
        if ($packageprofile_data->save()) {
            if (!empty($request->input('package'))) {
                $i = 1;
                foreach ($request->input('package') as $objPackage) {
                    $rules = array('package_name' => 'required', 'package_price' => 'required|integer');
                    $file = array('package_name' => $objPackage['package_name'], 'package_price' => $objPackage['package_price']);
                    $validator = Validator::make($file, $rules);
                    if (!$validator->fails()) {
                        if (!empty($objPackage['id'])) {
                            $package_data = Package::find($objPackage['id']);                            
                            if (!empty(Input::file('package_image_' . $i)) && Input::file('package_image_' . $i)->getError() == 0) {
                                $fileName = $this->fileUpload(Input::file('package_image_' . $i),$path, $package_data->image);
                            }                            
                        } else {
                            $package_data = new Package();
                            $fileName = "";
                            if (!empty(Input::file('package_image_' . $i)) && Input::file('package_image_' . $i)->getError() == 0) {
                                $fileName = $this->fileUpload(Input::file('package_image_' . $i), $path);
                            }
                            $package_data->image = $fileName;
                        }
                        $package_data->profile_id = $packageprofile_data->id;
                        $package_data->name = $objPackage['package_name'];
                        $package_data->price = $objPackage['package_price'];
                        $package_data->description = $objPackage['package_desc'];
                        $package_data->post_handling = $objPackage['ph'];
                        $package_data->save();
                    }
                    $i++;
                }
            }
            return Redirect::route('admin.packageprofile.index')->with(array('flash_message' => 'Package successfully Updated!', 'flash_action' => 'success'));
        } else {
            return Redirect::route('admin.packageprofile.edit', $id)->with(array('flash_message' => 'Package not updated successfully!', 'flash_action' => 'danger'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        die("hiii");
    }

}

resources/views/admin/packageprofile/list.blade.php
@extends('admin.layouts.master')
{{-- Page title --}}
@section('title')
Package Profile
@parent
@stop

{{-- page level styles --}}
@section('header_styles')

<link href="{{ asset('public/assets/css/pages/form2.css') }}" rel="stylesheet"/>
<link href="{{ asset('public/assets/css/pages/form3.css') }}" rel="stylesheet"/>
<link href="{{ asset('public/assets/vendors/jasny-bootstrap/css/jasny-bootstrap.min.css') }}" rel="stylesheet"/>
<link href="{{ asset('public/assets/vendors/intl-tel-input/build/css/intlTelInput.css') }}" rel="stylesheet"/>
<link href="{{ asset('public/assets/vendors/validation/dist/css/bootstrapValidator.min.css') }}" rel="stylesheet"/>
<style type='text/css'>
    .form-group.required .control-label:after { 
        content:"*";
        color:red;
    }
</style>
@stop

{{-- Page content --}}
@section('content')

<section class="content-header">
    <!--section starts-->
    <h1>Package Profile</h1>
</section>
<!--section ends-->
<section class="content">
    <div class="row">
        <div class="col-md-12">            
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="panel panel-primary filterable">
                <div class="panel-heading clearfix">
                    <div class="panel-heading clearfix  ">
                        <div class="caption pull-left">
                            <i class="livicon" data-name="list" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                            Package Profile List                        
                        </div>
                        <div class="btn-group pull-right">
                            <a href="{{route('admin.packageprofile.create')}}"  class=" btn btn-warning add-anc">Add New Package Profile</a>
                        </div>
                    </div>    
                </div>
                <div class="panel-body table-responsive">
                    @if (session('flash_message'))
                    <div class="flash-message">
                        <div class="alert alert-{{session('flash_action')}}">
                            <p>{{session('flash_message')}}</p>
                        </div>
                    </div>
                    @endif   
                    <form action="{{ route('admin.packageprofile.index') }}" method="GET" role="form">                    
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="action" value="" />
                    <div class="row">
                        <div class="col-xs-12 col-md-12">                                        
                            <div class="form-group {{ $errors->first('', 'has-error') }}">
                                    <label class="control-label">Search</label>
                                        <input type="text" name="search_keyword" id="search_keyword" class="form-control" style="width:320px;" placeholder="Search by package profile name" value="{{Request::input('search_keyword')}}">    
                                    <input type="submit" class="btn btn-primary" style="width:120px;margin-top:-58px;margin-left:404px;" value="Search">
                            </div>
                        </div>
                    </div> 
                    </form>   
                    <table class="table table-striped table-bordered" id="table-entity">
                        <thead>
                            <tr>                                    
                                <th style="width: 10%;text-align:center;">#</th>
                                <th style="width: 20%;text-align:center;">Package Profile Name</th>                                                                
                                <th style="text-align:center;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(!empty($packageprofile_data))                                                               
                            @foreach($packageprofile_data as $objEntity)
                            <tr>
                                <td style="text-align:center;">{{$objEntity['id']}}</td>                                    
                                <td style="text-align:left;">{{$objEntity['package_profile_name']}}</td>
                                <td style="width: 30%;text-align:center;">
<!--                                    <a href="{{URL('admin/package/create')}}?pp={{$objEntity['id']}}" id="edit" name="edit" class=" btn btn-warning add-anc">Add Package</a>
                                    <a href="{{URL('admin/package')}}?pp={{$objEntity['id']}}"  id="" class="btn btn-danger add-anc del-msg">List of Package</a>-->
                                    <a href="{{route('admin.packageprofile.edit',$objEntity['id'])}}" id="edit" name="edit" class=" btn btn-warning add-anc">Edit</a>
                                    <a href="{{route('admin.packageprofile.destroy',$objEntity['id'])}}"  id="" onclick="return confirm('Are you sure?');" class="btn btn-danger add-anc del-msg">Delete</a>
<!--                                    <a href="javascript:void(0)"  id="show_img" name="show_img" image-name="{{$objEntity['image']}}" class="show_img btn btn-info">View Image</a>-->
                                </td>
                            </tr>                                
                            @endforeach                            
                            @endif
                        </tbody>
                    </table>
                    <span style="width:100%;" class"pull-right">{!! $packageprofile_data->render() !!}</span>
                </div>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>     
</div>   
</section>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Package Profile Image</h4>
            </div>
            <div class="modal-body">
                <img width="100%" height="auto" id="show_img_src" src=""/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>      
        </div>
    </div>
</div>
<!-- global js -->
@stop

{{-- page level scripts --}}
@section('footer_scripts')    
<script src="{{ asset('public/assets/vendors/jasny-bootstrap/js/jasny-bootstrap.min.js') }}"
type="text/javascript"></script>
<script src="{{ asset('public/assets/vendors/validation/dist/js/bootstrapValidator.min.js') }}"
type="text/javascript"></script>
<script src="{{ asset('public/assets/vendors/intl-tel-input/build/js/intlTelInput.min.js') }}"
type="text/javascript"></script>
<script src="{{ asset('public/assets/js/pages/validation.js') }}" type="text/javascript"></script>
<script>        
    //"uploads/packageprofiles";
//    $(".show_img").click(function() {
//        var src = "{{url('/public/uploads/demo')}}";
//        var imagename = $(this).attr('image-name');
//        src = src + "/" + imagename;        
//        $("#show_img_src").attr("src", src);
//        $('#myModal').modal();
//    });
</script>


@stop